HosteriaSol/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("Galeria/", views.galeria, name="Galeria"),
    path("Nosotros/", views.nosotros, name="Nosotros"),
    path("Servicio/", views.servicios, name="Servicios"),
    path("Habitaciones/", views.habitaciones, name="Habitaciones"),
    path("contactar/", views.contactar, name="contactar"),
    path("administrador/", views.administrador, name="Administrador"),
    path('menu/', views.menu, name='menu'),
    path('logout/', views.logout, name='logout'),
    path("pago/<int:reserva_id>/<int:id_habitacion>/<int:servicio_id>/", views.pago, name="pago"),
    path("pago/<int:reserva_id>/<int:id_habitacion>/", views.pago, name="pago_sin_servicio"),
    path("confirmar_pago/", views.confirmar_pago, name="confirmar_pago"),
    path("terminos/", views.terminos, name="terminos"),

    
    #habitaciones
    path("habitacion/", views.habitacion, name="habitacion"),
    path("editar_habitacion/<int:id_habitacion>/", views.editar_habitacion, name="editar_habitacion"),
    path("agregar_habitacion/", views.agregar_habitacion, name="agregar_habitacion"),
    path("eliminar_habitacion/<int:id_habitacion>/",views.eliminar_habitacion, name="eliminar_habitacion"),
    path("seleccion_habitacion/<int:id_habitacion>/<int:reserva_id>/",views.seleccion_habitacion, name="seleccion_habitacion"),
    path("seleccion_habitacion_servicio/<int:id_habitacion>/<int:reserva_id>/<int:servicio_id>/", views.seleccion_habitacion, name="seleccion_habitacion_servicio"),
    path("eliminar_seleccion/<int:id_habitacion>/<int:reserva_id>/",views.eliminar_seleccion, name="eliminar_seleccion"),
    path("eliminar_seleccion_servicio/<int:id_habitacion>/<int:reserva_id>/<int:servicio_id>/",views.eliminar_seleccion, name="eliminar_seleccion_servicio"),
    
    
    #listar
    path("listar_habitaciones/", views.listar_habitaciones, name="listar_habitaciones"),
    path("listar_clientes/", views.listar_clientes, name="listar_clientes"),
    path("listar_servicios/", views.listar_servicios, name="listar_servicios"),
    path("listar_empleados/", views.listar_empleados, name="listar_empleados"),


    #empleados
    path("empleados/", views.empleados, name="empleados"),
    path("agregar_empleados/", views.agregar_empleados, name="agregar_empleados"),
    path("editar_empleados/<int:id_empleado>/", views.editar_empleados, name="editar_empleados"),
    path("eliminar_empleados/<int:id_empleado>/",views.eliminar_empleados, name="eliminar_empleados"),
    path("empleados/<int:id_empleado>/", views.empleados, name="empleados_id"),
    path("empleados/<int:id_empleado>/<int:reserva_id>/", views.empleados, name="empleados_id_reserva"),

    #Servicios
    path("agregar_servicio/", views.agregar_servicio, name="agregar_servicio"),
    path("editar_servicio/<int:id_servicio>/", views.editar_servicio, name="editar_servicio"),
    path("eliminar_servicio/<int:id_servicio>/",views.eliminar_servicio, name="eliminar_servicio"),     

    # clave
    path("cambiar_clave/", views.cambiar_clave, name="cambiar_clave"),
    path("Recuperar_clave/", views.Recuperar_clave, name="Recuperar_clave"),
    path("restablecer_contraseña/<str:correo>/", views.restablecer_contraseña, name="restablecer_contraseña"),


    # registros
    path("Register/", views.Register, name="Register"),
    path("registros/", views.usuarios, name="Registros"),
    path("agregar_registro/", views.agregar_usuario, name="agregar_registro"),
    path("eliminar_usuario/<int:id_usuario>/",views.eliminar_usuario, name="eliminar_usuario"),
    path("editar_registro/<int:id_usuario>/", views.editar_registro, name="editar_registro"),
    path("usuarios/", views.usuarios, name="usuarios"),


    # CRUD reservas
    path("Reservas2/<int:reserva_id>/<int:servicio_id>/", views.Reservas2, name="Reservas2"),
    path('Reservas2/<int:reserva_id>/', views.Reservas2, name='Reservas2_sin_servicio'),
    path("agregar_reservas", views.agregar_reservas, name="agregar_reservas"),
    path("eliminar_reserva/<int:id_reserva>/",views.eliminar_reserva, name="eliminar_reserva"),
    path('editar_reserva/<int:id_reserva>/<int:id_habitacion>/', views.editar_reserva, name='editar_reserva_hab'),
    path('editar_reserva/<int:id_reserva>/', views.editar_reserva, name='editar_reserva'),
    path("cancelar_reserva/<int:id_reserva>/",views.cancelar_reserva, name="cancelar_reserva"),
    path("detalle/<int:reserva_id>/<int:id_habitacion>/<int:servicio_id>/", views.detalles, name="detalles"),
    path("detalle/<int:reserva_id>/<int:id_habitacion>/", views.detalles, name="detalles_sin_servicio"),
    
]

HosteriaSolecito/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HosteriaSol.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HosteriaSol/models.py
from django.db import models

# Modelo de Usuario


class Usuario(models.Model):
    nombre = models.CharField(max_length=100)
    correo = models.EmailField(max_length=254, unique=True)
    password = models.CharField(max_length=254)

    TIPOS_DOCUMENTO = (
        (1, "Cedula de Ciudadania"),
        (2, "Tarjeta de Identidad"),
        (3, "Cedula de Extranjeria"),
        (4, "Pasaporte"),
    )
    tipo_documento = models.IntegerField(choices=TIPOS_DOCUMENTO, default=1)
    documento = models.CharField(max_length=20)
    foto = models.ImageField(upload_to="usuarios", default="usuarios/default.png", max_length=254)
    telefono = models.IntegerField(null=True)
    direccion = models.CharField(max_length=254)
    activo = models.BooleanField(default=False)
    ROLES = (
        (1, "Administrador"),
        (2, "Cliente"),
        (3, "Empleado"),
    )
    rol = models.IntegerField(choices=ROLES, default=2)

    def __str__(self):
        return f"{self.nombre} - {self.tipo_documento} ROL: {self.rol}"
    
    class Meta:
        ordering = ['-id']     
      

# Modelo de Servicio


class Servicio(models.Model):
    nombre = models.CharField(max_length=254)
    precio = models.DecimalField(max_digits=1000, decimal_places=0, default=0)
    descripcion = models.TextField(blank=False, null=False)
    hora_inicio = models.TimeField(help_text="HH:mm")
    hora_fin = models.TimeField(help_text="HH:mm")
    foto = models.ImageField(upload_to="servicios/", default="servicios/default.png", max_length=254)
    ESTADOS = (
        ("A", "Activo"),
        ("I", "Inactivo"),
    )
    estado = models.CharField(max_length=1, choices=ESTADOS, default="A")

    def __str__(self):
        return f"{self.nombre} - {self.precio} - {self.estado}"

    class Meta:
        ordering = ['-id'] 

# Modelo de Reserva
class Reserva(models.Model):
    cliente = models.ForeignKey("Usuario", on_delete=models.CASCADE, related_name="fk04_idCliente", null=False, blank=False)
    empleado = models.ForeignKey('Empleado', on_delete=models.SET_NULL, null=True, blank=True, related_name="fk05_idEmpleado")
    pago = models.ForeignKey('Pago', on_delete=models.SET_NULL, null=True, blank=True, related_name="fk06_idPago")
    adultos = models.IntegerField(null=True, blank=True)
    ninos = models.IntegerField(null=True, blank=True,default=0)
    fecha_inicio = models.DateField(help_text="AAAA-MM-DD", null=True, blank=True)
    fecha_fin = models.DateField(help_text="AAAA-MM-DD", null=True, blank=True)
    
    ESTADOS = (
        ("A", "ACTIVA"),
        ("I", "INACTIVA"),
        ("C", "CANCELADA"),
        ("P", "PAGADA"),
        ("V", "VENCIDA"),
    )
    estado = models.CharField(max_length=1, choices=ESTADOS, default="A")
    
    def __str__(self):
        txt = '{0} - {1} - {2}'
        return txt.format(self.cliente, self.empleado, self.estado)

    class Meta:
        ordering = ['-id']  
   


class Pago(models.Model):
    monto_total = models.DecimalField(max_digits=1000, decimal_places=0)
    fecha_pago = models.DateTimeField(null=True)
    METODOS =(
        (1,"EFECTIVO"),
        (2,"TRANSFERENCIA"),
        (3,"DATAFONO")
    )
    metodo_pago = models.IntegerField(choices=METODOS,default=1)

    def __str__(self):
        return f" {self.metodo_pago} - ${self.monto_total} ({self.fecha_pago})"


class Empleado(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    correo = models.EmailField(max_length=100)
    password = models.CharField(max_length=100, null=True, blank=True)
    foto = models.ImageField(upload_to="empleados", default="empleados/default.png", max_length=254)
    CARGOS = (
        ("Recepcionista", "RECEPCIONISTA"),
        ("Auxiliar_Aseo", "AUXILIAR_ASEO"),
        ("Tecnico_Mantenimiento", "TECNICO_MANTENIMIENTO"),
        ("Cocinero", "COCINERO"),
        ("Mesero", "MESERO"),
    )
    cargo = models.CharField(max_length=50, choices=CARGOS,default="Recepcionista")

    def __str__(self):
        return f"{self.nombre} {self.apellido}  {self.correo}  - {self.cargo}"
    
    class Meta:
        ordering = ['-id'] 


class Habitacion(models.Model):
    nombre = models.CharField(max_length=254)
    descripcion = models.TextField(null=True)
    capacidad = models.IntegerField()
    precio = models.FloatField(default=0)
    foto = models.ImageField(upload_to="habitaciones", default="habitaciones/default.png", max_length=254)
    ESTADOS = (
        ("D", "DISPONIBLE"),
        ("R", "RESERVADA"),
        ("L", "LIMPIEZA"),
    )
    estado = models.CharField(max_length=1, choices=ESTADOS, default="D")

    def __str__(self):
        return f"{self.nombre} - Capacidad: {self.capacidad} - Estado: {self.estado}"
    
    def to_dict(self):
        return {
            'id': self.id,
            'nombre': self.nombre,
            'descripcion': self.descripcion, 
            'precio': self.precio,
            'capacidad': self.capacidad,
            'estado': self.get_estado_display(),
            'foto': self.foto.url,
        }
    
    class Meta:
        ordering = ['-id'] 


class DetalleReserva(models.Model):
    habitacion = models.ForeignKey('Habitacion', on_delete=models.CASCADE, related_name="fk02_idHabitacion")
    reserva = models.ForeignKey('Reserva', on_delete=models.CASCADE, related_name="fk01_idReserva")
    cantidad = models.IntegerField(null=True)
    precio_neto = models.DecimalField(max_digits=10, decimal_places=0)
    servicio = models.ForeignKey('Servicio', on_delete=models.CASCADE, related_name="fk03_idServicio",null=True, blank=True)

    def __str__(self):
        return f"Reserva {self.reserva.id} - Habitación {self.habitacion.id} - Cantidad: {self.cantidad}"

HosteriaSol/templates/listar/listar_clientes.html
{% extends '-bases.html' %}
{% load static %}
{% block tittle %} Administrador {% endblock %}
{% block style %} {% static 'css/admin.css' %} {% endblock %}
{% block js %} {% static 'js/admin.js' %} {% endblock %}

{% block cuerpo %}  
<div class="container">
    <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Tablas
        </a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'Administrador' %}">Reservas</a></li>
            <li><a class="dropdown-item" href="{% url 'listar_habitaciones' %}">Habitaciones</a></li>
            <li><a class="dropdown-item" href="{% url 'listar_clientes' %}">Usuarios</a></li>
            <li><a class="dropdown-item" href="{% url 'listar_servicios' %}">Servicios</a></li>
            <li><a class="dropdown-item" href="{% url 'listar_empleados' %}">Empleados</a></li>
    </div>


    <a class="btn" href="{% url 'agregar_registro' %}">agregar</a>
    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>nombre</th>
                    <th>correo</th>
                    <th>tipo_documento</th>
                    <th>documento</th>
                    <th>foto</th>
                    <th>telefono</th>
                    <th>direccion</th>
                    <th>rol</th>
                    <th>accion</th>
                </tr>
            </thead>
            <tbody id="reservasTable">
                {% if data %}
                    {% for i in data %}
                    <tr>
                        <td>{{ i.id }}</td>
                        <td>{{ i.nombre }}</td>
                        <td>{{ i.correo }}</td>
                        <td>{{ i.get_tipo_documento_display }}</td>
                        <td>{{ i.documento }}</td>
                        <td><img src="{{ i.foto.url }}" class="fotico"></td>
                        <td>{{ i.telefono }}</td>
                        <td>{{ i.direccion }}</td>
                        <td>{{ i.get_rol_display }}</td>
                        <td>
                            <a class="bot" href="javascript:confirmar_eliminar(`{% url 'eliminar_usuario' i.id %}`);">Eliminar</a>
                            {% if i.rol != 3 %}
                                <a class="bot" href="{% url 'editar_registro' i.id %}">Editar</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="10" style="text-align: center;">No hay usuarios aún...</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
</div>

<script src="{% static 'js/admin.js' %}"></script>
{% endblock %}

HosteriaSol/templates/listar/listar_empleados.html
{% extends '-bases.html' %}
{% load static %}
{% block tittle %} Administrador {% endblock %}
{% block style %} {% static 'css/admin.css' %} {% endblock %}
{% block js %} {% static 'js/admin.js' %} {% endblock %}

{% block cuerpo %}  
<div class="container">
    <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Tablas
        </a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'Administrador' %}">Reservas</a></li>
            <li><a class="dropdown-item" href="{% url 'listar_habitaciones' %}">Habitaciones</a></li>
            <li><a class="dropdown-item" href="{% url 'listar_clientes' %}">Usuarios</a></li>
            <li><a class="dropdown-item" href="{% url 'listar_servicios' %}">Servicios</a></li>
            <li><a class="dropdown-item" href="{% url 'listar_empleados' %}">Empleados</a></li>
    </div>


    <a class="btn" href="{% url 'agregar_empleados' %}">agregar</a>
    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>nombre</th>
                    <th>apellido</th>
                    <th>correo</th>
                    <th>foto</th>
                    <th>cargo</th>
                    <th>accion</th>
                </tr>
            </thead>
            <tbody id="reservasTable">
                {% if data %}
                    {% for i in data %}
                    <tr>
                        <td>{{ i.id }}</td>
                        <td>{{ i.nombre }}</td>
                        <td>{{ i.apellido }}</td>
                        <td>{{ i.correo }}</td>
                        <td><img src="{{ i.foto.url }}" class="fotico"></td>
                        <td>{{ i.get_cargo_display }}</td>
                        <td>
                            <a class="bot" href="javascript:confirmar_eliminar(`{% url 'eliminar_empleados' i.id %}`);">Eliminar</a>
                            <a class="bot" href="{% url 'editar_empleados' i.id %}">Editar</a>
                        </td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="10" style="text-align: center;">No hay empleados aún...</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
</div>

<script src="{% static 'js/admin.js' %}"></script>
{% endblock %}

HosteriaSol/templates/listar/listar_habitaciones.html
{% extends '-bases.html' %}
{% load static %}
{% block tittle %} Administrador {% endblock %}
{% block style %} {% static 'css/admin.css' %} {% endblock %}
{% block js %} {% static 'js/habitaciones.js' %} {% endblock %}
{% block cuerpo %}  
<div class="container">
    <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Tablas
        </a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'Administrador' %}">Reservas</a></li>
            <li><a class="dropdown-item" href="{% url 'listar_habitaciones' %}">Habitaciones</a></li>
            <li><a class="dropdown-item" href="{% url 'listar_clientes' %}">Usuarios</a></li>
            <li><a class="dropdown-item" href="{% url 'listar_servicios' %}">Servicios</a></li>
            <li><a class="dropdown-item" href="{% url 'listar_empleados' %}">Empleados</a></li>
            
        </ul>
    </div>

    
    <a class="btn" href="{% url 'habitacion' %}">agregar</a>
    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">nombre</th>
                    <th scope="col">descripcion</th>
                    <th scope="col">capacidad</th>
                    <th scope="col">Foto</th>
                    <th scope="col">Precio</th>
                    <th scope="col">estado</th>
                    <th scope="col">accion</th>

                </tr>
                </thead>
                <tbody id="reservasTable">
                    {% if data %}
                    {% for i in data %}
                    <tr>
                        <td>{{ i.id }}</td>
                        <td>{{ i.nombre }}</td>
                        <td class="descripcion">{{ i.descripcion }}</td>
                        <td>{{ i.capacidad }}</td>
                        <td><img src="{{ i.foto.url }}" class="fotico"></td>
                        <td>{{ i.precio }}</td>
                        <td>{{ i.get_estado_display }}</td>
                        <td>
                            <a class="bot" href="javascript:confirmar_eliminar(`{% url 'eliminar_habitacion' i.id %}`);">Eliminar</a>
                            <a class="bot" href="{% url 'editar_habitacion' i.id %}">Editar</a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% else %}
                        <p>No hay habitacioes aún...</p>
                    {% endif %}
                </tbody>
            </thead>
        </table>
    </div>
</div>

<script src="{% static 'js/admin.js' %}"></script>
    
{% endblock %}

HosteriaSol/templates/listar/listar_servicios.html
{% extends '-bases.html' %}
{% load static %}
{% block tittle %}Administrador - Servicios{% endblock %}
{% block style %} {% static 'css/admin.css' %} {% endblock %}
{% block cuerpo %}
<div class="container">
    <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Tablas
        </a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'Administrador' %}">Reservas</a></li>
            <li><a class="dropdown-item" href="{% url 'listar_habitaciones' %}">Habitaciones</a></li>
            <li><a class="dropdown-item" href="{% url 'listar_clientes' %}">Usuarios</a></li>
            <li><a class="dropdown-item" href="{% url 'listar_servicios' %}">Servicios</a></li>
            <li><a class="dropdown-item" href="{% url 'listar_empleados' %}">Empleados</a></li>
    </div>
    
    <a class="btn" href="{% url 'agregar_servicio' %}">Agregar</a>
    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Precio</th>
                    <th>Hora inicio</th>
                    <th>Hora fin</th>
                    <th>Estado</th>
                    <th>Foto</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
                {% if data %}
                    {% for servicio in data %}
                    <tr>
                        <td>{{ servicio.id }}</td>
                        <td>{{ servicio.nombre }}</td>
                        <td class="descripcion">{{ servicio.descripcion }}</td>
                        <td>{{ servicio.precio }}</td>
                        <td>{{ servicio.hora_inicio }}</td>
                        <td>{{ servicio.hora_fin }}</td>
                        <td>{{ servicio.get_estado_display }}</td>
                        <td><img src="{{ servicio.foto.url }}" class="fotico"></td>
                        <td>
                            <a class="bot" href="javascript:confirmar_eliminar(`{% url 'eliminar_servicio' servicio.id %}`);">Eliminar</a>
                            <a class="bot" href="{% url 'editar_servicio' servicio.id %}">Editar</a>
                        </td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr><td colspan="9">No hay servicios aún...</td></tr>
                {% endif %}
            </tbody>
        </table>
    </div>
    
</div>
<script src="{% static 'js/admin.js' %}"></script>
{% endblock %}